spring.application.name=zorvyn
spring.datasource.url=jdbc:mysql://localhost:3307/my_database?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Hari@1807
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForJwtAuthenticationSystem12345
jwt.expiration=86400000
server.port=8081
server.servlet.context-path=/api/v1.0
server.tomcat.apr.enabled=
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha